### ISSUE TITLE
list_input_ports fails

### ISSUE THREAD

**Issue by gjover** [SpotlightKid/python-rtmidi#102]
Calling list_input_ports several times ends up failing.

This is a MWE:
```
import rtmidi.midiutil
for i in range(1000):
    rtmidi.midiutil.list_input_ports()
```

Output:

```
ALSA lib seq_hw.c:466:(snd_seq_hw_open) open /dev/snd/seq failed: Cannot allocate memory

MidiInAlsa::initialize: error creating ALSA sequencer client object.

Traceback (most recent call last):
  File "midid/rtmidi-test.py", line 6, in <module>
    rtmidi.midiutil.list_input_ports()
  File "/usr/lib/python3/dist-packages/rtmidi/midiutil.py", line 95, in list_input_ports
    midiin = rtmidi.MidiIn(get_api_from_environment(api))
  File "src/_rtmidi.pyx", line 728, in rtmidi._rtmidi.MidiIn.__cinit__
RuntimeError: MidiInAlsa::initialize: error creating ALSA sequencer client object.

```
rtmidi version 1.2.1

**Comment by SpotlightKid** [comment]
What does `arecordmidi -l' print?

**Comment by gjover** [comment]
Thank you!
