### ISSUE TITLE
MidiOutWinMM::openPort: error creating Windows MM MIDI output port.

### ISSUE THREAD

**Issue by matheusfillipe** [SpotlightKid/python-rtmidi#65]
Running the example from: http://trac.chrisarndt.de/code/wiki/python-rtmidi#Usageexample
Raises this:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "src\_rtmidi.pyx", line 589, in rtmidi._rtmidi.MidiBase.open_port
  File "src\_rtmidi.pyx", line 223, in rtmidi._rtmidi._cb_error_func
  File "src\_rtmidi.pyx", line 411, in rtmidi._rtmidi._default_error_handler
rtmidi._rtmidi.SystemError: MidiOutWinMM::openPort: error creating Windows MM MIDI output 
port.
```

And I am using a physical hardware keyboard as the output device. The same problem with midi Maper and midi loopback. The only that works is 'Microsoft GS Wavetable Synth 0'.

Running on windows 10.

**Comment by matheusfillipe** [comment]
I don't know what it was but working after rebooting. Everything is working fine now.
