### ISSUE TITLE
Import of version number fails when Python is run with -OO optimization

### ISSUE THREAD

**Issue by SpotlightKid** [SpotlightKid/python-rtmidi#69]
Via email from Geert Folkertsma:

I ran into a small bug when using the library, though: I have to use `python –OO` for performance reaons, which means docstrings are discarded. Since you cleverly extract description, long description etc from the docstring, this fails:

```
Python 3.7.3 (default, Apr 24 2019, 15:29:51) [MSC v.1915 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import rtmidi
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\ProgramData\Anaconda3\envs\ros2\lib\site-packages\rtmidi\__init__.py", line 3, in <module>
    from .release import version as __version__  # noqa
  File "C:\ProgramData\Anaconda3\envs\ros2\lib\site-packages\rtmidi\release.py", line 73, in <module>
    description = __doc__.splitlines()
AttributeError: 'NoneType' object has no attribute 'splitlines'
```

**Comment by SpotlightKid** [comment]
I have released version [1.4.3](https://github.com/SpotlightKid/python-rtmidi/releases/tag/1.4.3) with this fix.
