### ISSUE TITLE
install fails with pypy3

### ISSUE THREAD

**Issue by cyberic99** [SpotlightKid/python-rtmidi#96]
Hi,
I'm using archlinux, and tried to install python-rtmidi using pypy (https://www.pypy.org/)
```
$ pypy3 -mpip install --user python-rtmidi --verbose
User install by explicit request
Created temporary directory: /tmp/pip-ephem-wheel-cache-t6kgpxoh
Created temporary directory: /tmp/pip-req-tracker-djqr4x89
Initialized build tracking at /tmp/pip-req-tracker-djqr4x89
Created build tracker: /tmp/pip-req-tracker-djqr4x89
Entered build tracker: /tmp/pip-req-tracker-djqr4x89
Created temporary directory: /tmp/pip-install-54ae70br
1 location(s) to search for versions of python-rtmidi:
* https://pypi.org/simple/python-rtmidi/
Fetching project page and analyzing links: https://pypi.org/simple/python-rtmidi/
Getting page https://pypi.org/simple/python-rtmidi/
Found index url https://pypi.org/simple
Looking up "https://pypi.org/simple/python-rtmidi/" in the cache
Request header has "max_age" as 0, cache bypassed
Starting new HTTPS connection (1): pypi.org:443
https://pypi.org:443 "GET /simple/python-rtmidi/ HTTP/1.1" 304 0
[...]
  Using cached python-rtmidi-1.4.9.tar.gz (251 kB)
  Added python-rtmidi from https://files.pythonhosted.org/packages/92/bf/749468bc43f85ec77f37154327360ba82e7d0ae622341eab44a6d75751c3/python-rtmidi-1.4.9.tar.gz#sha256=bfeb4ed99d0cccf6fa2837566907652ded7adc1c03b69f2160c9de4082301302 to build tracker '/tmp/pip-req-tracker-djqr4x89'
    Running setup.py (path:/tmp/pip-install-54ae70br/python-rtmidi/setup.py) egg_info for package python-rtmidi
    Created temporary directory: /tmp/pip-pip-egg-info-_m7w3kl8
    Running command python setup.py egg_info
    Compiling src/_rtmidi.pyx because it depends on /home/od/.local/lib/pypy3.7/site-packages/Cython/Includes/libcpp/vector.pxd.
    [1/1] Cythonizing src/_rtmidi.pyx
    running egg_info
    creating /tmp/pip-pip-egg-info-_m7w3kl8/python_rtmidi.egg-info
    writing /tmp/pip-pip-egg-info-_m7w3kl8/python_rtmidi.egg-info/PKG-INFO
    writing dependency_links to /tmp/pip-pip-egg-info-_m7w3kl8/python_rtmidi.egg-info/dependency_links.txt
    writing top-level names to /tmp/pip-pip-egg-info-_m7w3kl8/python_rtmidi.egg-info/top_level.txt
    writing manifest file '/tmp/pip-pip-egg-info-_m7w3kl8/python_rtmidi.egg-info/SOURCES.txt'
    reading manifest file '/tmp/pip-pip-egg-info-_m7w3kl8/python_rtmidi.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    Detected JACK version 0.125.
    JACK version is recent enough to have 'jack_port_rename' function.
    warning: no previously-included files found matching '.appveyor.yml'
    warning: no previously-included files found matching '.travis.yml'
    warning: no previously-included files found matching '*.rst.in'
    no previously-included directories found matching 'ci'
    warning: no previously-included files matching '__pycache__' found under directory '*'
    warning: no previously-included files matching '*.py[co]' found under directory '*'
    writing manifest file '/tmp/pip-pip-egg-info-_m7w3kl8/python_rtmidi.egg-info/SOURCES.txt'
  Source in /tmp/pip-install-54ae70br/python-rtmidi has version 1.4.9, which satisfies requirement python-rtmidi from https://files.pythonhosted.org/packages/92/bf/749468bc43f85ec77f37154327360ba82e7d0ae622341eab44a6d75751c3/python-rtmidi-1.4.9.tar.gz#sha256=bfeb4ed99d0cccf6fa2837566907652ded7adc1c03b69f2160c9de4082301302
  Removed python-rtmidi from https://files.pythonhosted.org/packages/92/bf/749468bc43f85ec77f37154327360ba82e7d0ae622341eab44a6d75751c3/python-rtmidi-1.4.9.tar.gz#sha256=bfeb4ed99d0cccf6fa2837566907652ded7adc1c03b69f2160c9de4082301302 from build tracker '/tmp/pip-req-tracker-djqr4x89'
Using legacy setup.py install for python-rtmidi, since package 'wheel' is not installed.
Installing collected packages: python-rtmidi
  Created temporary directory: /tmp/pip-record-op4wlluq
    Running command /usr/bin/pypy3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-54ae70br/python-rtmidi/setup.py'"'"'; __file__='"'"'/tmp/pip-install-54ae70br/python-rtmidi/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-op4wlluq/install-record.txt --single-version-externally-managed --user --prefix= --compile --install-headers /home/od/.local/include/pypy3.7/python-rtmidi

    Detected JACK version 0.125.
    JACK version is recent enough to have 'jack_port_rename' function.
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.7
    creating build/lib.linux-x86_64-3.7/rtmidi
    copying rtmidi/version.py -> build/lib.linux-x86_64-3.7/rtmidi
    copying rtmidi/midiutil.py -> build/lib.linux-x86_64-3.7/rtmidi
    copying rtmidi/midiconstants.py -> build/lib.linux-x86_64-3.7/rtmidi
    copying rtmidi/__init__.py -> build/lib.linux-x86_64-3.7/rtmidi
    running egg_info
    writing python_rtmidi.egg-info/PKG-INFO
    writing dependency_links to python_rtmidi.egg-info/dependency_links.txt
    writing top-level names to python_rtmidi.egg-info/top_level.txt
    reading manifest file 'python_rtmidi.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    warning: no previously-included files found matching '.appveyor.yml'
    warning: no previously-included files found matching '.travis.yml'
    warning: no previously-included files found matching '*.rst.in'
    no previously-included directories found matching 'ci'
    warning: no previously-included files matching '__pycache__' found under directory '*'
    warning: no previously-included files matching '*.py[co]' found under directory '*'
    writing manifest file 'python_rtmidi.egg-info/SOURCES.txt'
    running build_ext
    building 'rtmidi._rtmidi' extension
    creating build/temp.linux-x86_64-3.7
    creating build/temp.linux-x86_64-3.7/src
    creating build/temp.linux-x86_64-3.7/src/rtmidi
    gcc -pthread -DNDEBUG -O2 -fPIC -D__RTMIDI_SILENCE_WARNINGS__ -D__LINUX_ALSA__ -D__UNIX_JACK__ -DJACK_HAS_PORT_RENAME -Isrc -Isrc/rtmidi -I/opt/pypy3/include -c src/_rtmidi.cpp -o build/temp.linux-x86_64-3.7/src/_rtmidi.o
    In file included from src/_rtmidi.cpp:676:
    src/pyinit.h: In function 'void py_init()':
    src/pyinit.h:18:9: error: 'Py_Initialize' was not declared in this scope; did you mean 'Py_IsInitialized'?
       18 |         Py_Initialize();
          |         ^~~~~~~~~~~~~
          |         Py_IsInitialized
    error: command 'gcc' failed with exit status 1
    Running setup.py install for python-rtmidi ... error
ERROR: Command errored out with exit status 1: /usr/bin/pypy3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-54ae70br/python-rtmidi/setup.py'"'"'; __file__='"'"'/tmp/pip-install-54ae70br/python-rtmidi/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-op4wlluq/install-record.txt --single-version-externally-managed --user --prefix= --compile --install-headers /home/od/.local/include/pypy3.7/python-rtmidi Check the logs for full command output.
Exception information:
Traceback (most recent call last):
  File "/home/od/.local/lib/pypy3.7/site-packages/pip/_internal/req/req_install.py", line 841, in install
    req_description=str(self.req),
  File "/home/od/.local/lib/pypy3.7/site-packages/pip/_internal/operations/install/legacy.py", line 86, in install
    raise LegacyInstallFailure
pip._internal.operations.install.legacy.LegacyInstallFailure

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/od/.local/lib/pypy3.7/site-packages/pip/_internal/cli/base_command.py", line 188, in _main
    status = self.run(options, args)
  File "/home/od/.local/lib/pypy3.7/site-packages/pip/_internal/cli/req_command.py", line 185, in wrapper
    return func(self, options, args)
  File "/home/od/.local/lib/pypy3.7/site-packages/pip/_internal/commands/install.py", line 407, in run
    use_user_site=options.use_user_site,
  File "/home/od/.local/lib/pypy3.7/site-packages/pip/_internal/req/__init__.py", line 71, in install_given_reqs
    **kwargs
  File "/home/od/.local/lib/pypy3.7/site-packages/pip/_internal/req/req_install.py", line 845, in install
    six.reraise(*exc.parent)
  File "/home/od/.local/lib/pypy3.7/site-packages/pip/_vendor/six.py", line 703, in reraise
    raise value
  File "/home/od/.local/lib/pypy3.7/site-packages/pip/_internal/operations/install/legacy.py", line 76, in install
    cwd=unpacked_source_directory,
  File "/home/od/.local/lib/pypy3.7/site-packages/pip/_internal/utils/subprocess.py", line 274, in runner
    spinner=spinner,
  File "/home/od/.local/lib/pypy3.7/site-packages/pip/_internal/utils/subprocess.py", line 241, in call_subprocess
    raise InstallationError(exc_msg)
pip._internal.exceptions.InstallationError: Command errored out with exit status 1: /usr/bin/pypy3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-54ae70br/python-rtmidi/setup.py'"'"'; __file__='"'"'/tmp/pip-install-54ae70br/python-rtmidi/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-op4wlluq/install-record.txt --single-version-externally-managed --user --prefix= --compile --install-headers /home/od/.local/include/pypy3.7/python-rtmidi Check the logs for full command output.
```
pypy3 is supposed to have the same API as cpython 3.7

After this error with python-rtmidi==1.4.9, I tried to downgrade and I was able to install python-rtmidi version 1.4.6 with pypy3

**Comment by SpotlightKid** [comment]
It looks like pypy3 does not provide the `Py_Initialize` C API function, even though it, as you say, is supposed to have the same API as cpython 3.7.

It seems that [pyinit.h](https://github.com/SpotlightKid/python-rtmidi/blob/master/src/pyinit.h)  needs to be adapted to detect PyPy.

**Comment by cyberic99** [comment]
Do you think I should report this to pypy's team @SpotlightKid ?

**Comment by SpotlightKid** [comment]
Yes, I think it would be good to get their opinion on whether they consider this a bug or just something that is not supported.

Their header files still have `PyEval_InitThreads`, which is deprecated from CPython 3.6, so that can be used in `pyinit.h`. Here's a tentative fix: 4935b084157b2c5f15e6425d86b68d5098ef1168

To test, check out the repo and run the same command as you used above, in the repo root, with `.` (dot)  instead of `python-rtmidi`.

**Comment by cyberic99** [comment]
This command:
``
pypy3 -mpip install --user . --verbose --upgrade
``
fails:
```
   building 'rtmidi._rtmidi' extension
    creating build/temp.linux-x86_64-3.7
    creating build/temp.linux-x86_64-3.7/src
    creating build/temp.linux-x86_64-3.7/src/rtmidi
    gcc -pthread -DNDEBUG -O2 -fPIC -D__RTMIDI_SILENCE_WARNINGS__ -D__LINUX_ALSA__ -D__UNIX_JACK__ -DJACK_HAS_PORT_RENAME -Isrc -Isrc/rtmidi -I/opt/pypy3/include -c src/_rtmidi.cpp -o build/temp.linux-x86_64-3.7/src/_rtmidi.o
    src/_rtmidi.cpp:676:10: fatal error: RtMidi.h: No such file or directory
      676 | #include "RtMidi.h"
          |          ^~~~~~~~~~
    compilation terminated.
    error: command 'gcc' failed with exit status 1
    Running setup.py install for python-rtmidi ... error
  Rolling back uninstall of python-rtmidi
  Moving to /home/od/.local/lib/pypy3.7/site-packages/python_rtmidi-1.4.9.dev0-py3.7.egg-info
   from /home/od/.local/lib/pypy3.7/site-packages/~ython_rtmidi-1.4.9.dev0-py3.7.egg-info
  Moving to /home/od/.local/lib/pypy3.7/site-packages/rtmidi/
   from /home/od/.local/lib/pypy3.7/site-packages/~tmidi
  Replacing /home/od/.local/lib/pypy3.7/site-packages/python_rtmidi-1.4.9.dev0-py3.7.egg-info from /home/od/.local/lib/pypy3.7/site-packages/~ython_rtmidi-1.4.9.dev0-py3.7.egg-info
  Replacing /home/od/.local/lib/pypy3.7/site-packages/rtmidi/ from /home/od/.local/lib/pypy3.7/site-packages/~tmidi
ERROR: Command errored out with exit status 1: /usr/bin/pypy3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-q8rb4nnt/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-q8rb4nnt/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-3vzw9bsp/install-record.txt --single-version-externally-managed --user --prefix= --compile --install-headers /home/od/.local/include/pypy3.7/python-rtmidi Check the logs for full command output.
Exception information:
Traceback (most recent call last):
  File "/home/od/.local/lib/pypy3.7/site-packages/pip/_internal/req/req_install.py", line 841, in install
    req_description=str(self.req),
  File "/home/od/.local/lib/pypy3.7/site-packages/pip/_internal/operations/install/legacy.py", line 86, in install
    raise LegacyInstallFailure
pip._internal.operations.install.legacy.LegacyInstallFailure

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/od/.local/lib/pypy3.7/site-packages/pip/_internal/cli/base_command.py", line 188, in _main
    status = self.run(options, args)
  File "/home/od/.local/lib/pypy3.7/site-packages/pip/_internal/cli/req_command.py", line 185, in wrapper
    return func(self, options, args)
  File "/home/od/.local/lib/pypy3.7/site-packages/pip/_internal/commands/install.py", line 407, in run
    use_user_site=options.use_user_site,
  File "/home/od/.local/lib/pypy3.7/site-packages/pip/_internal/req/__init__.py", line 71, in install_given_reqs
    **kwargs
  File "/home/od/.local/lib/pypy3.7/site-packages/pip/_internal/req/req_install.py", line 845, in install
    six.reraise(*exc.parent)
  File "/home/od/.local/lib/pypy3.7/site-packages/pip/_vendor/six.py", line 703, in reraise
    raise value
  File "/home/od/.local/lib/pypy3.7/site-packages/pip/_internal/operations/install/legacy.py", line 76, in install
    cwd=unpacked_source_directory,
  File "/home/od/.local/lib/pypy3.7/site-packages/pip/_internal/utils/subprocess.py", line 274, in runner
    spinner=spinner,
  File "/home/od/.local/lib/pypy3.7/site-packages/pip/_internal/utils/subprocess.py", line 241, in call_subprocess
    raise InstallationError(exc_msg)
pip._internal.exceptions.InstallationError: Command errored out with exit status 1: /usr/bin/pypy3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-q8rb4nnt/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-q8rb4nnt/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-3vzw9bsp/install-record.txt --single-version-externally-managed --user --prefix= --compile --install-headers /home/od/.local/include/pypy3.7/python-rtmidi Check the logs for full command output.
WARNING: You are using pip version 20.1.1; however, version 21.1.2 is available.
You should consider upgrading via the '/usr/bin/pypy3 -m pip install --upgrade pip' command.
```
This one succeeds:
``pypy3 -mpip install --user git+https://github.com/SpotlightKid/python-rtmidi.git --upgrade``
so it seems you fixed it @SpotlightKid

**Comment by SpotlightKid** [comment]
The first probably command failed, because you didn't check out the `rtmidi` Git sub-module. If you like, you can do ` git submodule update --init` in your checkout and try again.

**Comment by cyberic99** [comment]
> If you like, you can do git submodule update --init in your checkout and try again.

yep it worked, thanks!
